pizzas/urls.py
from django.urls import path

from . import views

app_name = 'pizzas'

urlpatterns = [
    path('', views.index, name='index'),
    path('pizzas/', views.pizzas, name='pizzas'),
    path('pizza/<int:pizza_id>', views.pizza, name='pizza')
]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls'))
]

pizzas/models.py
from django.db import models


class Pizza(models.Model):
    name = models.CharField(max_length=200)
    
    class Meta:
        verbose_name = 'Pizza'
        verbose_name_plural = 'Pizzas'
    
    
    def __str__(self):
        return self.name
    
    
class Topping(models.Model):
    pizza = models.ManyToManyField(Pizza)
    name = models.CharField(max_length=200)
    
    class Meta:        
        verbose_name = 'Topping'
        verbose_name_plural = 'Toppings'
        
    def __str__(self):
        return self.name
    
    
    

    
    

pizzas/views.py
from django.shortcuts import render
from .models import Pizza, Topping


def index(request):
    title = 'Pizza'
    context = {'title': title}
    return render(
        request=request,
        template_name='pizzas/index.html',
        context=context
        )
    
def pizzas(request):
    pizzas = Pizza.objects.all()
    context = {'pizzas': pizzas}
    
    return render(
        request=request,
        template_name='pizzas/pizzas.html',
        context=context
                  )
    
def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.all()
    context = {'pizza': pizza, 'toppings': toppings }
    
    return render(
        request=request,
        template_name='pizzas/pizza.html',
        context=context
                  )

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'pizzas/css/main.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <p>
        <a href="{% url 'pizzas:index' %}">Pizzeria</a> - 
        <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
    </p>

    {% block content %}  {% endblock %}
</body>
</html>

templates/pizzas/index.html
{% extends 'base.html' %}

<h1>{% block title %}Main page{% endblock %}</h1>


{% block content %}{% endblock %}

templates/pizzas/pizza.html
{% extends 'base.html' %}

<h1>{% block title %}Pizza - {{ pizza }}{% endblock %}</h1>



{% block content %}


    <h1>Pizza: {{ pizza }}</h1>
    <ul>
        {% for toping in toppings %}
            <li>{{ toping }}</li>
        {% empty %}
            <p>Not yet</p>
        {% endfor %}
    </ul>
    


{% endblock %}

templates/pizzas/pizzas.html
{% extends 'base.html' %}

<h1>{% block title %}Pizzas{% endblock %}</h1>



{% block content %}

    <div .class="pizza">

        <h1>Pizzas:</h1>
    
        <ul>
            {% for pizza in pizzas %}
                <li><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></li>
            {% empty %}
                <p>Not yet</p>
            {% endfor %}
        </ul>
    </div>
    
    


{% endblock %}